volumes:
    db-data:
        driver: local

services:
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
                DOCKER_CONTENT_TRUST: 1
        ports:
            - '8080:80'
            - '5173:5173'
        volumes:
            - .:/app
        environment:
            PHP_IDE_CONFIG: serverName=sealbase_server
    db:
        build: ./docker/db
        environment:
            MYSQL_DATABASE: sealbase_db
            MYSQL_USER: sealbase
            MYSQL_PASSWORD: secret
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            TZ: 'Asia/Tokyo'
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/db/init:/docker-entrypoint-initdb.d
        ports:
            - '3306:3306'
    redis:
        image: valkey/valkey:8.1
        container_name: 'redis_cbm'
        ports:
            - '6379:6379'
